#!/bin/bash

#PBS -q normal
#PBS -l select=1:ncpus=16:mem=64GB
#PBS -l walltime=24:00:00
#PBS -P Personal 
#PBS -N STAR_Indexing
#PBS -o /home/users/ntu/muhamma4/output/STAR_Indexing.o
#PBS -e /home/users/ntu/muhamma4/output/STAR_Indexing.e

workingDir=/home/users/ntu/muhamma4/scratch/BS6202/reference
GENOME_DIR=${workingDir}/Homo_sapiens/NCBI/GRCh38/STAR/
fastaPath=${workingDir}/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa
annotationPath=${workingDir}/Homo_sapiens/NCBI/GRCh38/Annotation/Genes.gencode/genes.gtf
NumberOfThreads=16

module load anaconda3/2022.10
source activate /home/users/ntu/muhamma4/.conda/envs/BS6214-2

cd /home/users/ntu/muhamma4/scratch/tmp

STAR --runThreadN $NumberOfThreads \
     --runMode genomeGenerate \
     --genomeDir $genomeDir \
     --genomeFastaFiles $fastaPath \
     --sjdbGTFfile $annotationPath \
     --sjdbOverhang 100

source deactivate 