#!/bin/bash

#PBS -q normal
#PBS -l select=1:ncpus=4:mem=12GB
#PBS -l walltime=24:00:00
#PBS -P Personal 
#PBS -N multiqc.STAR
#PBS -o /home/users/ntu/muhamma4/Masters_Output/multiqc.STAR.o
#PBS -e /home/users/ntu/muhamma4/Masters_Output/multiqc.STAR.e

module load anaconda3/2022.10
source activate /home/users/ntu/muhamma4/.conda/envs/multiqc

cd outPath='/home/users/ntu/muhamma4/scratch/BS6202/STAR_result/multiqc_results/'

multiqc --file-list  /home/users/ntu/muhamma4/masters_scripts/STAR_dir_list.txt

