#!/bin/bash

#PBS -q normal
#PBS -l select=1:ncpus=16:mem=64GB
#PBS -l walltime=24:00:00
#PBS -P Personal 
#PBS -N STAR_BS6202
#PBS -o /home/users/ntu/muhamma4/output/STAR_BS6202.o
#PBS -e /home/users/ntu/muhamma4/output/STAR_BS6202.e

referenceDir=/home/users/ntu/muhamma4/scratch/BS6202/reference
rawPath='/home/users/ntu/muhamma4/scratch/BS6202/raw_data/'
outPath='/home/users/ntu/muhamma4/scratch/BS6202/STAR_result/'

GENOME_DIR=${referenceDir}/Homo_sapiens/NCBI/GRCh38/STAR/
GTF_FILE=${referenceDir}/Homo_sapiens/NCBI/GRCh38/Annotation/Genes.gencode/genes.gtf
THREADS=16

function process_STAR {
	PREFIX=$3
	echo $(date +"%Y-%m-%d %H:%M:%S") " - STAR PROCESSING ${PREFIX}"
	STAR --genomeDir $GENOME_DIR --sjdbGTFfile $GTF_FILE --readFilesIn $1 $2 --runThreadN $THREADS --twopassMode Basic --outSAMtype BAM SortedByCoordinate --readFilesCommand zcat --outFileNamePrefix $3 1>$3-STAR.o 2>$3-STAR.e
	
	mv ${PREFIX}Aligned.sortedByCoord.out.bam $RESULTS/${PREFIX}.out.bam
	echo $(date +"%Y-%m-%d %H:%M:%S") " - STAR COMPLETED ${PREFIX}"
}

function create_folder {
  	if [ -d $1 ]; then
    	rm -r $1
  	fi
  	mkdir $1
}

module load anaconda3/2022.10
source activate /home/users/ntu/muhamma4/.conda/envs/BS6214-2

x='_1.fastq.gz'
y='_2.fastq.gz'

cat /home/users/ntu/muhamma4/masters_scripts/sra_list.txt | while read p
do
	cd $outPath
	create_folder $p
	cd $p

	process_STAR $rawPath$p$x $rawPath$p$y $p
done
